export const types = {
  SET_LANGUAJE: "SET_LANGUAJE",
  SET_TIME_PER_QUESTION: "SET_TIME_PER_QUESTION",
  SET_CURRENT_LANGUAJE: "SET_CURRENT_LANGUAJE",
  SET_QUESTION_LIST: "SET_QUESTION_LIST",
  SET_CURRENT_QUESTION: "SET_CURRENT_QUESTION",
  SET_REMOVE_QUESTION: "SET_REMOVE_QUESTION",
  SET_SHOW_RECORD_MODAL: "SET_SHOW_RECORD_MODAL",
  SET_HIDE_RECORD_MODAL: "SET_HIDE_RECORD_MODAL",
  SET_DATA_LANGUAJES: "SET_DATA_LANGUAJES",
  SET_LANGUAJE_OPTIONS: "SET_LANGUAJE_OPTIONS",
  RELOAD_LANGUAJES: "RELOAD_LANGUAJES",
};
