export const types = {
  SET_CAMERA_RECORD_SENDED: "SET_CAMERA_RECORD_SENDED",
  SET_SCREEN_RECORD_SENDED: "SET_SCREEN_RECORD_SENDED",
  SET_CAMERA_RECORD_LINK: "SET_CAMERA_RECORD_LINK",
  SET_SCREEN_RECORD_LINK: "SET_SCREEN_RECORD_LINK,",
  SET_EMAIL_SENDED: "SET_EMAIL_SENDED",
  CLEAR_RECORD_INFO: "CLEAR_RECORD_INFO",
};
